% -----------------------------------------------------------------------------
% Load reader memory map files for shared data interpretation
function [ ...
    control_mm, ...
    incoming_mm_header, incoming_mm_data, ...
    todo_mm_header, todo_mm_data] = apply_structure()
    control_mm = ...
        memmapfile('_Control.dat', ...
        'Format', {...
            'int32' double([1 1]) 'is_terminated'; ...
            'int32' double([1 1]) 'header_size'; ...
            'uint64' double([1 1]) 'timestamp'; ...
            % TODO: Define control fields
            }, ...
        'Repeat', 1, ...
        'Writable', false);

    % -------------------------------------------------------------------------
    % Load reader memory map file for incoming data
    incoming_mm_header = ...
        memmapfile('_TodoInc.dat', ...
        'Format', {...
            'int64' double([1 1]) 'max_size_bytes'; ...
            'int64' double([1 1]) 'element_size_bytes'; ...
            'int64' double([1 1]) 'write_head'; ...
            'uint64' double([1 1]) 'start_time'; ...
            'single' double([1 2]) 'sensor_origin'; ...
            'uint64' double([1 1]) 'rotation_time_msec'; ...
            }, ...
        'Repeat', 1, ...
        'Writable', false);
    % ---
    incoming_end_index = int64(incoming_mm_header.Data(1).max_size_bytes / incoming_mm_header.Data(1).element_size_bytes);
    incoming_mm_data = ...
        memmapfile('_TodoInc.dat', ...
        'Format', {...
            % TODO: Define field structure of the incoming data
            }, ...
        'Offset', control_mm.Data(1).header_size, ...
        'Repeat', incoming_end_index, ...
        'Writable', false);

    % -------------------------------------------------------------------------
    % Load writer memory map file for outgoing TODO data
    todo_mm_header = ...
        memmapfile('_TodoOut.dat', ...
        'Format', {...
            'int64' double([1 1]) 'max_size_bytes'; ...
            'int64' double([1 1]) 'element_size_bytes'; ...
            'int64' double([1 1]) 'write_head'; ...
            'uint64' double([1 1]) 'start_time'; ...
            'single' double([1 2]) 'sensor_origin'; ...
            'uint64' double([1 1]) 'rotation_time_msec'; ...
            }, ...
        'Repeat', 1, ...
        'Writable', true);
    % ---
    todo_end_index = int64(todo_mm_header.Data(1).max_size_bytes / todo_mm_header.Data(1).element_size_bytes);
    todo_mm_data = ...
        memmapfile('_TodoOut.dat', ...
        'Format', {...
            % TODO: Define field structure of the outgoing data
            }, ...
        'Offset', control_mm.Data(1).header_size, ...
        'Repeat', 1, ...
        'Writable', true);
    % -------------------------------------------------------------------------
end
