% -----------------------------------------------------------------------------
% Load reader memory map file for incoming data
function [mm_header, mm_data] = apply_structure(file_sequence)
    mm_header = ...
        memmapfile(strcat('_Raw_', int2str(file_sequence), '.dat'), ...
        'Format', {...
            'int64' double([1 1]) 'max_size_bytes'; ...
            'int64' double([1 1]) 'element_size_bytes'; ...
            'int64' double([1 1]) 'write_start'; ...
            'int64' double([1 1]) 'write_head'; ...
            'uint64' double([1 1]) 'start_time'; ...
            'single' double([1 2]) 'sensor_origin'; ...
            'uint64' double([1 1]) 'rotation_time_msec'; ...
            }, ...
        'Repeat', 1, ...
        'Writable', false);
    % -------------------------------------------------------------------------
    mm_data = ...
        memmapfile(strcat('_Raw_', int2str(file_sequence), '.dat'), ...
        'Format', {...
            'uint64' double([1 1]) 'sequence_block'; ...
            'uint64' double([1 1]) 'timestamp'; ...
            'single' double([1 1]) 'range'; ...
            'single' double([1 1]) 'azimuth'; ...
            'single' double([1 1]) 'speed'; ...
            'single' double([1 1]) 'intensity'; ...
            }, ...
        'Offset', 4096, ...
        'Repeat', int64(mm_header.Data(1).max_size_bytes / mm_header.Data(1).element_size_bytes), ...
        'Writable', false);
    % -------------------------------------------------------------------------
end
