% -----------------------------------------------------------------------------
% Load reader memory map file for incoming data
function [ ...
    control_mm, ...
    incoming_mm_header, incoming_mm_data, ...
    tracks_mm_header, tracks_mm_data] = apply_structure()
    control_mm = ...
        memmapfile('_Control.dat', ...
        'Format', {...
            'int32' double([1 1]) 'is_terminated'; ...
            'int32' double([1 1]) 'header_size'; ...
            'uint64' double([1 1]) 'timestamp'; ...
            'int32' double([1 1]) 'required_detections'; ...
            }, ...
        'Repeat', 1, ...
        'Writable', false);
    % -------------------------------------------------------------------------
    % Load reader memory map file for incoming data
    incoming_mm_header = ...
        memmapfile('_Plots.dat', ...
        'Format', {...
            'int64' double([1 1]) 'max_size_bytes'; ...
            'int64' double([1 1]) 'element_size_bytes'; ...
            'int64' double([1 1]) 'write_head'; ...
            'uint64' double([1 1]) 'start_time'; ...
            'single' double([1 2]) 'sensor_origin'; ...
            'uint64' double([1 1]) 'rotation_time_msec'; ...
            }, ...
        'Repeat', 1, ...
        'Writable', false);
    % -------------------------------------------------------------------------
    incoming_end_index = int64(incoming_mm_header.Data(1).max_size_bytes / incoming_mm_header.Data(1).element_size_bytes);
    incoming_mm_data = ...
        memmapfile('_Plots.dat', ...
        'Format', {...
            'uint64' double([1 1]) 'timestamp'; ...
            'single' double([1 1]) 'latitude'; ...
            'single' double([1 1]) 'longitude'; ...
            'single' double([1 1]) 'range'; ...
            'single' double([1 1]) 'azimuth'; ...
            'single' double([1 1]) 'speed'; ...
            'int32' double([1 1]) 'type'; ...
            }, ...
        'Offset', control_mm.Data(1).header_size, ...
        'Repeat', incoming_end_index, ...
        'Writable', false);
    % -------------------------------------------------------------------------
    % Load writer memory map file for outgoing trakcs data
    tracks_mm_header = ...
        memmapfile('_Tracks.dat', ...
        'Format', {...
            'int64' double([1 1]) 'max_size_bytes'; ...
            'int64' double([1 1]) 'element_size_bytes'; ...
            'int64' double([1 1]) 'write_head'; ...
            'uint64' double([1 1]) 'start_time'; ...
            'single' double([1 2]) 'sensor_origin'; ...
            'uint64' double([1 1]) 'rotation_time_msec'; ...
            }, ...
        'Repeat', 1, ...
        'Writable', true);
    % -------------------------------------------------------------------------
    tracks_end_index = int64(tracks_mm_header.Data(1).max_size_bytes / tracks_mm_header.Data(1).element_size_bytes);
    tracks_mm_data = ...
        memmapfile('_Tracks.dat', ...
        'Format', {...
            'uint8' double([24 tracks_end_index]) 'time'; ...
            'uint8' double([5 tracks_end_index]) 'identifier'; ...
            'single' double([1 tracks_end_index]) 'latitude'; ...
            'single' double([1 tracks_end_index]) 'longitude'; ...
            'single' double([1 tracks_end_index]) 'bearing'; ...
            'single' double([1 tracks_end_index]) 'speed'; ...
            'uint32' double([1 tracks_end_index]) 'type'; ...
            'uint8' double([254 tracks_end_index]) 'info'; ...
            }, ...
        'Offset', control_mm.Data(1).header_size, ...
        'Repeat', 1, ...
        'Writable', true);
    % -------------------------------------------------------------------------
end
